version: '3.8'

services:
  db:
    image: postgres:14
    container_name: cynaris_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dee18
      POSTGRES_DB: cynaris_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cynaris_backend
    environment:
      DB_NAME: cynaris_db
      DB_USER: postgres
      DB_PASS: dee18
      DB_HOST: db
      PORT: 5000
      JWT_SECRET: your_secret_key
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
